/**
 * The last payload each screen successfully received, kept so it can be shown again when the
 * network cannot supply a fresh one.
 *
 * WHY THIS EXISTS ALONGSIDE THE PERSISTED RTK CACHE
 * -------------------------------------------------
 * store/index.js persists the RTK Query cache, which already survives a reload — but it is
 * not a reliable offline store, for two reasons:
 *
 *   - `keepUnusedDataFor: 0` on the live endpoints (app fees, loans) drops the entry the
 *     moment the last subscriber unmounts, so navigating away and coming back offline leaves
 *     nothing at all.
 *   - the persisted cache is evicted and rewritten on RTK's schedule, not on "was this the
 *     last thing the user successfully saw".
 *
 * This is deliberately dumb by comparison: one key, one payload, one timestamp, written only
 * when a request genuinely succeeded. It is a fallback for display, never a source of truth —
 * nothing is ever submitted from it.
 *
 * Every access is wrapped: localStorage throws in Safari private mode and when the origin's
 * quota is exhausted, and a saved copy that cannot be read is not a reason to fail to render.
 */

const PREFIX = 'barip:offline:';

/** @returns {{ data: unknown, at: number } | null} */
export const readOffline = (key) => {
  if (!key) return null;

  try {
    const raw = window.localStorage.getItem(PREFIX + key);
    if (!raw) return null;

    const parsed = JSON.parse(raw);
    // Shape-checked rather than trusted: this is data from a previous version of the app,
    // and a half-written or outdated entry must not take the page down.
    if (!parsed || typeof parsed !== 'object' || !('data' in parsed)) return null;

    return { data: parsed.data, at: Number(parsed.at) || 0 };
  } catch {
    return null;
  }
};

export const writeOffline = (key, data) => {
  if (!key || data === undefined) return;

  try {
    window.localStorage.setItem(PREFIX + key, JSON.stringify({ data, at: Date.now() }));
  } catch {
    // Almost always QuotaExceededError. Drop every offline entry rather than guess which one
    // matters least — they are all regenerated by the next successful request, and a storage
    // that is full is worse than one that is empty.
    try {
      Object.keys(window.localStorage)
        .filter((k) => k.startsWith(PREFIX))
        .forEach((k) => window.localStorage.removeItem(k));
    } catch {
      // Nothing further to try; the app renders fine without a saved copy.
    }
  }
};

/** Used on sign-out: one account's data must never be shown to the next person to log in. */
export const clearOffline = () => {
  try {
    Object.keys(window.localStorage)
      .filter((k) => k.startsWith(PREFIX))
      .forEach((k) => window.localStorage.removeItem(k));
  } catch {
    // ignored
  }
};
