import {
  COLORS,
  PAGE,
  TYPE,
  createSurface,
  dataTable,
  documentHeader,
  factRow,
  pageFooter,
  sectionHeading,
} from './pdf';

/**
 * Generate the system administration overview PDF.
 *
 * Ported off jsPDF onto the shared toolkit in utils/pdf. This export had the Bengali problem
 * worse than the others: its "Recently added properties" table prints a house name, its
 * address and its owner's name straight from the database, so on this platform most of that
 * table was mojibake. The admin's own name in the header had the same fault.
 *
 * It also prints the taka sign. U+09F3 sits in the Bengali block, so it cannot be drawn by
 * the built-in Latin faces at all - pdf-lib throws on it rather than dropping it - and it is
 * what routes every money cell to the embedded Bengali face, which does carry the glyph.
 *
 * Returns the surface, so the caller chooses: `.save(name)` to download, `.toBase64()` to
 * send it somewhere.
 */
export async function generateSystemReportPdf({ data, generatedBy, money }) {
  const { quickStats, platform, operations, systemOverview, recentActivities } = data;
  const recentHouses = recentActivities?.recentHouses ?? [];

  const surface = await createSurface({ content: { generatedBy, recentHouses } });

  const left = PAGE.marginX;
  const width = PAGE.width - PAGE.marginX * 2;

  const header = documentHeader(surface, {
    tagline: 'System Administration Dashboard',
    documentType: 'SYSTEM OVERVIEW',
  });

  const facts = factRow(surface, {
    x: left,
    y: header.endY + 8,
    width,
    facts: [
      { label: 'GENERATED BY', values: [generatedBy || '-'] },
      { label: 'GENERATED', values: [new Date().toLocaleString('en-US')] },
      { label: 'CLASSIFICATION', values: ['Confidential'] },
    ],
  });

  // ── Key metrics ──────────────────────────────────────────────────────────
  sectionHeading(surface, 'Key metrics', left, facts.endY + 10, {
    size: TYPE.sectionHeading + 2, color: COLORS.brand,
  });

  const metrics = dataTable(surface, {
    x: left,
    y: facts.endY + 14,
    width,
    variant: 'filled',
    striped: true,
    headFill: COLORS.ink,
    head: ['Metric', 'Value', 'Status'],
    // The metric name needs the room; the other two are short and sit right.
    columns: [{ width: 0.46, align: 'left' }, { width: 0.27, align: 'right' }, { align: 'right' }],
    fontSize: TYPE.bodySmall,
    headFontSize: TYPE.bodySmall - 0.5,
    rowHeight: 7.2,
    padding: 3.5,
    rows: [
      ['Total users', String(quickStats.totalUsers), 'Active'],
      ['Total houses', String(quickStats.totalHouses), 'Operational'],
      ['Total flats', String(quickStats.totalFlats), 'Recorded'],
      // 'System Health 100% Excellent' and a server-load reading used to sit here. Neither
      // was measured. What replaces them is measured.
      ['Occupied flats', `${platform.occupiedFlats} of ${platform.totalFlats}`, `${platform.occupancyRate}%`],
      ['Rent collected (month)', money(platform.rentCollectedThisMonth), 'Received'],
      [
        'Rent outstanding',
        money(platform.rentOutstanding),
        platform.rentOverdueCount > 0 ? `${platform.rentOverdueCount} overdue` : 'None overdue',
      ],
      [
        'Email queue',
        `${operations.emailPending} pending`,
        operations.emailFailed > 0 ? `${operations.emailFailed} failed` : 'Healthy',
      ],
      [
        'Background jobs',
        `${operations.jobsPending} pending`,
        operations.jobsFailed > 0 ? `${operations.jobsFailed} failed` : 'Healthy',
      ],
    ],
  });

  // ── Role distribution ────────────────────────────────────────────────────
  const roles = systemOverview?.roleDistribution ?? [];
  let flowY = metrics.endY;

  if (roles.length) {
    sectionHeading(surface, 'Role distribution', left, flowY + 12, {
      size: TYPE.sectionHeading + 2, color: COLORS.brand,
    });
    flowY = dataTable(surface, {
      x: left,
      y: flowY + 16,
      // Half width: a two-column count table stretched across the page leaves a run of
      // whitespace between the label and its number that the eye has to cross.
      width: width / 2,
      variant: 'filled',
      striped: true,
      headFill: COLORS.muted,
      head: ['Role', 'Count'],
      columns: [{ width: 0.68, align: 'left' }, { align: 'right' }],
      fontSize: TYPE.bodySmall,
      headFontSize: TYPE.bodySmall - 0.5,
      rowHeight: 7.2,
      padding: 3.5,
      rows: roles.map((r) => [r.role, String(r.count)]),
    }).endY;
  }

  // ── Recently added properties ────────────────────────────────────────────
  if (recentHouses.length) {
    sectionHeading(surface, 'Recently added properties', left, flowY + 12, {
      size: TYPE.sectionHeading + 2, color: COLORS.brand,
    });
    flowY = dataTable(surface, {
      x: left,
      y: flowY + 16,
      width,
      variant: 'filled',
      striped: true,
      headFill: COLORS.ink,
      head: ['House', 'Address', 'Owner', 'Created'],
      columns: [
        { width: 0.24, align: 'left' },
        { width: 0.3, align: 'left' },
        { width: 0.28, align: 'left' },
        { align: 'right' },
      ],
      fontSize: TYPE.bodySmall,
      headFontSize: TYPE.bodySmall - 0.5,
      rowHeight: 7.2,
      padding: 3.5,
      rows: recentHouses.map((h) => [
        h.name ?? '-',
        h.address ?? '-',
        h.owner?.name ?? '-',
        h.createdAt ? new Date(h.createdAt).toLocaleDateString('en-US') : '-',
      ]),
    }).endY;
  }

  pageFooter(surface, { parts: ['Bari Porichalona — confidential'] });

  return surface;
}

/** The filename the export downloads as. */
export function systemReportFileName() {
  return `System_Overview_${new Date().toISOString().slice(0, 10)}.pdf`;
}
